// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0cZAWb8BG9ql2VkUcLDnOFUl2lvB7Pk',
    appId: '1:308114670799:web:998e221dd3698dd12f23ba',
    messagingSenderId: '308114670799',
    projectId: 'flow-43f6c',
    authDomain: 'flow-43f6c.firebaseapp.com',
    storageBucket: 'flow-43f6c.appspot.com',
    measurementId: 'G-EQ2VL1612F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_ktgVGB5Nf9JaXxlZ85IM9LSUQGHACQ',
    appId: '1:308114670799:android:80885200bccb45d32f23ba',
    messagingSenderId: '308114670799',
    projectId: 'flow-43f6c',
    storageBucket: 'flow-43f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzyOQkDaAMBkvuxQQTAJMFfHqVaOdNZ0',
    appId: '1:308114670799:ios:7ba308e6139d99ca2f23ba',
    messagingSenderId: '308114670799',
    projectId: 'flow-43f6c',
    storageBucket: 'flow-43f6c.appspot.com',
    iosBundleId: 'com.cheng.flowapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOzyOQkDaAMBkvuxQQTAJMFfHqVaOdNZ0',
    appId: '1:308114670799:ios:4e3c7060507c8dbb2f23ba',
    messagingSenderId: '308114670799',
    projectId: 'flow-43f6c',
    storageBucket: 'flow-43f6c.appspot.com',
    iosBundleId: 'com.example.flowApp.RunnerTests',
  );
}
